[package]
name = "bgfx"
version = "0.1.0"
authors = ["Johan Sköld <johan@skold.cc>"]

[dependencies]
bitflags = "1.2.1"
libc = "0.2.71"

[dependencies.bgfx-sys]
path = "./bgfx-sys"

[dev-dependencies]
cgmath = "0.17.0"
glutin = "0.24.1"
time = "0.2.16"
winit = "0.22.2"
raw-window-handle = "0.3.3"
